BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT plan(8);
INSERT INTO auth.users(id,email) VALUES('eeeeeeee-0000-0000-0000-000000000001','aifoundationa@test.local'),('eeeeeeee-0000-0000-0000-000000000002','aifoundationb@test.local');
INSERT INTO public.ai_settings(user_id,generation_model) VALUES('eeeeeeee-0000-0000-0000-000000000001','local:4b');
SET LOCAL ROLE authenticated;
SET LOCAL request.jwt.claims='{"sub":"eeeeeeee-0000-0000-0000-000000000002","role":"authenticated"}';
SELECT is_empty('SELECT 1 FROM public.ai_settings','AI settings isolated');
SELECT throws_ok($$INSERT INTO public.ai_settings(user_id) VALUES('eeeeeeee-0000-0000-0000-000000000001')$$,'42501',NULL,'cannot write another owner settings');
SELECT throws_ok($$SELECT public.acquire_ai_lease()$$,'42501',NULL,'GPU lease is service-only');
RESET ROLE;
SELECT is(public.check_request_limit('test:rate',1,60),true,'first request allowed');
SELECT is(public.check_request_limit('test:rate',1,60),false,'second request rate-limited');
CREATE TEMP TABLE holder AS SELECT public.acquire_ai_lease() id;
SELECT isnt((SELECT id FROM holder),NULL::uuid,'first GPU caller acquires lease');
SELECT is(public.acquire_ai_lease(),NULL::uuid,'second GPU caller cannot overlap');
SELECT public.release_ai_lease((SELECT id FROM holder));
SELECT isnt(public.acquire_ai_lease(),NULL::uuid,'lease released for next caller');
SELECT * FROM finish();
ROLLBACK;
