BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT plan(11);
INSERT INTO auth.users(id,email) VALUES('abababab-0000-0000-0000-000000000001','cataloga@test.local'),('abababab-0000-0000-0000-000000000002','catalogb@test.local');
SET LOCAL ROLE authenticated;
SET LOCAL request.jwt.claims='{"sub":"abababab-0000-0000-0000-000000000001","role":"authenticated"}';
SELECT lives_ok($$SELECT public.create_catalog('abababab-1000-0000-0000-000000000001','{"work":{"title":"Atomic book","work_type":"book"},"record":{"record_type":"edition"},"identifiers":[{"scheme":"isbn","value":"9780261103252"}],"credits":[{"kind":"person","display_name":"Jane Writer","family_name":"Writer","sort_name":"Writer, Jane","match_key":"writer","role":"author"}],"tags":["Science"],"lockCredits":true}')$$,'catalog creation succeeds');
SELECT is((SELECT count(*)::int FROM public.works),1,'one work committed');
SELECT is((SELECT count(*)::int FROM public.record_tags),1,'tag committed with record');
SELECT is((SELECT count(*)::int FROM public.record_contributors),1,'credits committed with record');
SELECT lives_ok($$SELECT public.create_catalog('abababab-1000-0000-0000-000000000001','{"work":{"title":"Atomic book","work_type":"book"},"record":{"record_type":"edition"},"identifiers":[{"scheme":"isbn","value":"9780261103252"}],"credits":[{"kind":"person","display_name":"Jane Writer","family_name":"Writer","sort_name":"Writer, Jane","match_key":"writer","role":"author"}],"tags":["Science"],"lockCredits":true}')$$,'lost response replays');
SELECT throws_ok($$SELECT public.create_catalog('abababab-1000-0000-0000-000000000001','{"work":{"title":"Changed book","work_type":"book"},"record":{"record_type":"edition"}}')$$,'23514','request ID bound to different catalog input','changed replay rejected');
SELECT throws_ok($$SELECT public.create_catalog('abababab-1000-0000-0000-000000000002','{"work":{"title":"Rollback book","work_type":"book"},"record":{"record_type":"edition"},"credits":[{"kind":"person","display_name":"Incomplete name"}]}')$$,'P0001','invalid contributor','invalid credit aborts whole transaction');
SELECT is((SELECT count(*)::int FROM public.works),1,'failed catalog left no orphan work');
SET LOCAL request.jwt.claims='{"sub":"abababab-0000-0000-0000-000000000002","role":"authenticated"}';
SELECT throws_ok($$SELECT public.create_catalog(gen_random_uuid(),'{"expectedOwner":"abababab-0000-0000-0000-000000000001","work":{"title":"Old account payload","work_type":"book"},"record":{"record_type":"edition"}}')$$,'42501','account changed','late import cannot write to a different signed-in account');
SELECT is_empty('SELECT id FROM public.catalog_requests','second user cannot read another replay payload');
SELECT throws_ok($$INSERT INTO public.catalog_requests(user_id,id,payload,result) VALUES('abababab-0000-0000-0000-000000000001',gen_random_uuid(),'{}','{}')$$,'42501',NULL,'second user cannot write replay rows');
SELECT * FROM finish();
ROLLBACK;
